from db.meetings import *

SCHEDULE = [
    [
        None,
        CHEMISTRY,
        ENGLISH,
        PHYSICS,
        PHYSICS,
        PHYSICS,
        SOCIAL_STUDIES,
        ENGLISH,
        None,
        COMPUTER_SCIENCE_MODULE,
    ],
    [
        COMPUTER_SCIENCE,
        COMPUTER_SCIENCE,
        LITERATURE,
        RUSSIAN,
        PHYSICAL_EDUCATION,
        HISTORY,
        RUSSIAN,
        None,
    ],
    [
        PHYSICAL_EDUCATION,
        BIOLOGY,
        BIOLOGY,
        GEOMETRY,
        GEOMETRY,
        ALGEBRA,
        ALGEBRA,
        HISTORY,
    ],
    [
        GEOGRAPHY,
        LITERATURE,
        ALGEBRA,
        GERMAN,
        LITERATURE,
        SOCIAL_STUDIES,
        ALGEBRA,
        None
    ],
    [
        GEOMETRY,
        GEOMETRY,
        ENGLISH,
        PHYSICS,
        COMPUTER_SCIENCE,
        COMPUTER_SCIENCE,
        GERMAN,
        None,
    ],
    [

    ],
    [

    ]
]
